### ISSUE TITLE
Midi Knobs/Sliders

### ISSUE THREAD

**Issue by cepko33** [mmckegg/loop-drop-app#111]
I have been working on a script for my grid, the Livid Block[0] and I have not yet been able to find support for non-button midi controls. I am always tweaking synth and mix parameters, so having more midi control would be super.

[0]http://www.musiciansfriend.com/pro-audio/livid-block-midi-controller/485471

**Comment by cepko33** [comment]
After some investigation I found https://github.com/mmckegg/loop-mpkmini/blob/master/index.js#L64-L79, maybe it could be lifted into a new module

**Comment by mmckegg** [comment]
Completely forgot that I'd done that for mpk! And yes I agree. 

I haven't yet had a good think about how to connect knobs up to things in loop drop. There is the idea of param linking, so if knobs could somehow expose themselves as modulators, then everything would just work. 

Really open to ideas/input here!

**Comment by mmckegg** [comment]
Here's something I've been playing around with: https://github.com/loopjs/launch-control

![](https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSsxhlg9rFT44-bOviYvdgFg8BqmymgQPevOXiw12Tewdier6bEtg)

It can be linked in using [extend.js](https://github.com/mmckegg/loop-drop-app/blob/master/extend.js)

It's the idea of global controllers. Rather than being attached to a particular setup, they get full control over all setups.

I'm using this one for switching between songs, changing tempo, and global params than can be routed in each setup.

**Comment by mmckegg** [comment]
These can now be added as global controllers. See [nodes/global-launch-control/object.js](https://github.com/mmckegg/loop-drop-app/blob/master/nodes/global-launch-control/object.js#L88)

This method also works on loop grid controllers too.

Closing.
