### ISSUE TITLE
add explicit license

### ISSUE THREAD

**Issue by mmckegg** [mmckegg/loop-drop-app#93]
It's currently ISC but not obvious anywhere.

Also opening up the discussion of maybe a better license to use?

Some debate ensued yesterday here: http://www.reddit.com/r/javascript/comments/39znvu/loop_drop/

I know @ahdinosaur has some opinions :) I'm willing to hear them out!

**Comment by ahdinosaur** [comment]
- [general backstory of my opinion as a blog post](https://blog.dinosaur.is/workers-of-open-source-unite/)
- [related discussion of value networks for software](https://www.loomio.org/d/kNYDWoqR/value-networks-for-software)

the problem is that a permissive license provides no protection against someone else (who might have never contributed and could even have opposing values to you) reaping the rewards of your two years of labor and capturing all future value of your work.

the goal is a license where only those who contribute to the project may [reap rewards in proportion to their contribution](http://p2pfoundation.net/Category:Peerproduction). using something like sustain as mentioned in #94 is a good step, although i wonder if it only works when there is a supplementary license to enforce the value network. this is a grey area as it's all still being pioneered.

the other, more established way to protect your open source product is to license it with a copyleft license (GPL, AGPL, ...) and maybe have a contributor license agreement that allows you to change licenses in the future. the intention is that anyone who improves your product must also provide their changes under the same copyleft license, thus being a viral infection that open sources anything it touches.

in [Enspiral](http://enspiral.com)'s [current open source products](https://github.com/open-app/core#the-apps), we use AGPLv3, as in our opinion it's the best we got until a better peer production license comes around.

**Comment by mmckegg** [comment]
I am definitely warming up to GPL. Starting to think that I will do loop-drop-app as some sort of GPL license but all the low level modules continue to offer under BSD style.

**Comment by oshi-shinobu** [comment]
Any updates on this issue? I too recommend using the GPL, and please remember to add "or any later version" to avoid potential license incompatibilities.

But GPL or not, you should add a LICENSE or COPYING file to the root directory of this project containing the full license text as soon as possible and state the licensing in the README file. Right now some people might think this program is proprietary and avoid it, because the licensing is not obvious.

**Comment by mmckegg** [comment]
@oshi-shinobu: been too busy writing code :laughing: but will get on to this real soon! Hopefully this week. Pretty sure it's gonna end up being GPL.
